### ISSUE TITLE
Doesn't save with original .lu file names

### ISSUE THREAD

**Issue by crustycrabthe3rd** [0BuRner/corona-archiver#1]
When i run the program, it doesn't unpack the files to their original file names. Instead file names look like this file-offset.extracted. Would be cool if you made it unpack each file with its original name.

**Comment by 0BuRner** [comment]
Hi @Ra2fat ,

There is two ways for reading the file. The first one uses the file stream and the other one uses the index section which contains filenames. So in fact it was already implemented. But I forgot to set it as default method x)

I updated the script 9ee7b92 and now the default method will extract the files with their correct names ;-)
If you have any other issue, don't hesitate to create a new one here.

Thanks for your feedback !

**Comment by crustycrabthe3rd** [comment]
Thank you =D
