### ISSUE TITLE
problem unpacking resource.car

### ISSUE THREAD

**Issue by Vensere** [0BuRner/corona-archiver#10]
Hello, 
Thank you for creating this programm. I have a problem unpacking a car file.
I tried python versions 2.7.16 and 3.7 but the unpacking proccess ends up with error:
`Traceback (most recent call last):
  File "C:\corona-archiver-master\corona-archiver.py", line 238, in <module>
    archiver.unpack(input_file=input, output_dir=os.path.join(output, ''))
  File "C:\corona-archiver-master\corona-archiver.py", line 104, in unpack
    self._read_data_idx()
  File "C:\corona-archiver-master\corona-archiver.py", line 194, in _read_data_idx
    self._read_data_entry(offset, filename, True, True)
  File "C:\corona-archiver-master\corona-archiver.py", line 186, in _read_data_entry
    self._write_data_entry(content, offset if offset else self.stream.tell(), filename)
  File "C:\corona-archiver-master\corona-archiver.py", line 211, in _write_data_entry
    new_filename = str(filename, 'utf-8')
TypeError: str() takes at most 1 argument (2 given)`

**Comment by 0BuRner** [comment]
Hello @Vensere,
Can you share a link to the file you are trying to unpack and the exact command line you used? It will be easier for me to check what's going on.
Thank you

**Comment by Vensere** [comment]
Thank you for replying
i tried 3 ways to execute the command `corona-archiver.py -u resource.car out` , `corona-archiver.py -u resource.car out/` and `corona-archiver.py -u resource.car out\` 
both resource.car and folder "out" are in the same folder with corona-archiver.py

https://drive.google.com/open?id=1VoBa9hDKVqCX0rJzNQpTgBlBAp47QbVy

**Comment by 0BuRner** [comment]
Hi,
I looked at your issue and it's pretty weird... 
I managed to successfully unpack your file without any modification to the code (I git clone this repo on a new computer - python 3.7.4 on Windows). Here is the result: https://we.tl/t-Qa3kbA0Iun
Maybe try to put resources.car and out/ in different folders... Or maybe you're running Linux ?

**Comment by Vensere** [comment]
Hello,
putting resources.car and out/ in different folders fixed the problem
Thank you
