### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by QM4RS** [0BuRner/corona-archiver#13]
Hi. i don't know how to tnx for this tool! it's really good but it's not working anymore :(
Here it't log : 
Traceback (most recent call last):
  File "corona-archiver.py", line 238, in <module>
  File "corona-archiver.py", line 104, in unpack
  File "corona-archiver.py", line 194, in _read_data_idx
  File "corona-archiver.py", line 186, in _read_data_entry
  File "corona-archiver.py", line 215, in _write_data_entry
FileNotFoundError: [Errno 2] No such file or directory: 'out\\Scenes.TribeManager.lu'
[4412] Failed to execute script corona-archiver

**Comment by 0BuRner** [comment]
Hello,
It seems you're trying to unpack a LU file but it is not the purpose of this tool. It only works with .car files.
Your LU file is probably the compiled version, so you will have to decompile it. To do so, check the README file and the following tutorials: https://github.com/0BuRner/corona-archiver#dissasembling
Anyway, your issue here is that you did not provide the correct path to the file. Put the full path of the file and it should work.
Regards

**Comment by QM4RS** [comment]
> Hello, It seems you're trying to unpack a LU file but it is not the purpose of this tool. It only works with .car files. Your LU file is probably the compiled version, so you will have to decompile it. To do so, check the README file and the following tutorials: https://github.com/0BuRner/corona-archiver#dissasembling Anyway, your issue here is that you did not provide the correct path to the file. Put the full path of the file and it should work. Regards



here again my log : 

C:\Users\mahdi\OneDrive\Desktop\Corona Archiver>corona-archiver.exe -u "C:\Users\mahdi\OneDrive\Desktop\Corona Archiver\resource.car" out
Traceback (most recent call last):
  File "corona-archiver.py", line 238, in <module>
  File "corona-archiver.py", line 104, in unpack
  File "corona-archiver.py", line 194, in _read_data_idx
  File "corona-archiver.py", line 186, in _read_data_entry
  File "corona-archiver.py", line 215, in _write_data_entry
FileNotFoundError: [Errno 2] No such file or directory: 'out\\Scenes.TribeManager.lu'
[22864] Failed to execute script corona-archiver

after run the script , there is no out folder to decompile lua files

**Comment by 0BuRner** [comment]
Thank you for full logs, it is more meaningful now :) 
Yes it seems there is an error when unpacking that file. Either the file is wrongly compiled or the version of the archive is unsupported by corona-archiver right now.
Can you provide a link to the .car file so I can download it and check what's going wrong and update the code if needed ?

**Comment by QM4RS** [comment]
> Thank you for full logs, it is more meaningful now :) Yes it seems there is an error when unpacking that file. Either the file is wrongly compiled or the version of the archive is unsupported by corona-archiver right now. Can you provide a link to the .car file so I can download it and check what's going wrong and update the code if needed ?

Your project is not a problem. Before proceeding with the extraction, I create the folder in which I want the files to be extracted. If you would like, I can easily solve this issue with a simple if-else statement, so that other friends won't encounter this problem. Thank you for sharing such a great project ❤️
