### ISSUE TITLE
Help with unpacking & decompiling

### ISSUE THREAD

**Issue by CODLOP** [0BuRner/corona-archiver#3]
hello,
i can't use it, i have python 3.6.4 and when write command line with cmd i get error "Syntax Error: invalid syntax"
and i installed 2.7 and when write command line like this "corona-archiver.py -u resource.car C:\corona-archiver" i get msg "Extraction done" but i not find anything in folder, 
please help me to fix it and what problem, in python version or i write command wrong ?

**Comment by 0BuRner** [comment]
Hi @AitGamers , I haven't tested the tool with Python 3 if I remember correctly. so it may not work with Python 3+.

1. So with Python 2.7, can you try with these steps :
  1.1. Create folder **temp** in C:\
  1.2 Create folder **unpacked** in C:\temp\
  1.3. Copy your file **resource.car** to C:\temp\
  1.4. Type the following command: `corona-archiver.py -u C:\temp\resource.car C:\temp\unpacked\`
2. Can you share a link of the file you try to unpack? So I can take a look on what's going wrong.

**Comment by CODLOP** [comment]
thank you very much, its work
i get .lu files inside unpacked
but all .lu files is encrypted 
any method to decrypt it ?
i can upload file for you if you want it 

thank you again <3

**Comment by 0BuRner** [comment]
Yes, please share your files.
I guess they are not encrypted but compiled, that's why you can't read them as a readable 'text' file. 
There are 1 or 2 open source lua decompiler available. You should try them to get what you need :-) 
What's your final goal?

**Comment by CODLOP** [comment]
download it from here [resource.car](https://mega.nz/#!VY4RnDAT!Ipi19WUK2x2UiKO2S4lGcAYZE-pWpirWLRtJaoNDWM8)

my final goal is reverse engineer a android game (Word Search & Crossword Puzzle)

update : i find tool to decompile lua files, but corona archiver tool give me .lu not .lua
how can I deal with that

**Comment by 0BuRner** [comment]
This is just a name, the file extension doesn't matter. It's a metadata, an indication of what file type it is.
Just like you can rename a .zip to .png. The content of the file will not change and it the file is still a zip. You just lost the information it's a zip file.

You can try to rename them to .lua if the decompiler you found need it. Otherwise, just try to decompile them as it.
