### ISSUE TITLE
can't unpack car file

### ISSUE THREAD

**Issue by bazickoff** [0BuRner/corona-archiver#4]
I need help to unpack car file   https://www.dropbox.com/s/aky63mvmhvp48aq/resource.car?dl=0

when I run the command line  nothing happens

**Comment by 0BuRner** [comment]
Can you copy/paste the exact command line you're using ? And also the directory in which you execute the command.
Thanks

**Comment by bazickoff** [comment]
It works fine now with python 2.7 

the problem was with python 3.6 , it seems your script not compatible with python 3.6
