### ISSUE TITLE
Can't pack lua back to resource.car

### ISSUE THREAD

**Issue by alex15964** [0BuRner/corona-archiver#6]
As title
I pack lua back to resource.car, the resource.car file is only 1kb (original file is 236)
Even I didn't edit those lua files, then just pack back, it's still 1 kb.

**Comment by 0BuRner** [comment]
Hello,
What's the command line you're using?
Can you give a like to an archive containing lua files or the initial .car file? I'll try to pack them.

**Comment by alex15964** [comment]
resource.car: https://drive.google.com/open?id=145IyRRa08QpJTapphTmKfIdPCvGVj7Rm

1.unpack
CMD line: corona-archiver.exe -u resource.car rs (path: Desktop\apk)
CA unpacked those lu files at "Desktop\apk" but "Desktop\apk\rs" ( there is a empty folder named rs), and all lua files was named like rsXXX.lu

2.pack
CMD line: corona-archiver.exe -p rs rs.car (path: Desktop\apk\rs)
 I moved all lu files into rs folder.  CA created rs.car, but it was only 1 KB.

**Comment by 0BuRner** [comment]
The link you gave isn't working anymore. Can you fix it or give another link ? I haven't had the time try until today.

**Comment by alex15964** [comment]
fix already: https://drive.google.com/open?id=145IyRRa08QpJTapphTmKfIdPCvGVj7Rm
thx for help :D

**Comment by 0BuRner** [comment]
Hi, I think I found your issue :p I made the same mistake while trying on my side. 
You have to append a '\\' char at the end of your output directory.
1. `corona-archiver.exe -u resource.car rs\` (path: Desktop\apk\)
2. `corona-archiver.exe -p rs\ rs\rs.car` **(path: Desktop\apk\)**

These commands should work.
Let me know if it worked ;-)

**Comment by 0BuRner** [comment]
By the way, I fixed the code and the Windows binary. Thus now it should work even if you don't specify that '\\' character =)

**Comment by alex15964** [comment]
it's worked, thx.
