### ISSUE TITLE
how it work :)

### ISSUE THREAD

**Issue by bazickoff** [0BuRner/corona-archiver#8]
hello, thank you for this script  I followed your guide 
https://github.com/0BuRner/corona-archiver/issues/3

this is the file   https://www.dropbox.com/s/7zhun4omdyj1yaj/resource.car?dl=0

I'm using python 2.7.16

I get this error is there something wrong with my command

C:\Users\HOUSSAM\Desktop\corona-archiver-master>python corona-archiver.py -u C:\
temp\resource.car C:\temp\unpacked\
Traceback (most recent call last):
  File "corona-archiver.py", line 238, in <module>
    archiver.unpack(input_file=input, output_dir=os.path.join(output, ''))
  File "corona-archiver.py", line 104, in unpack
    self._read_data_idx()
  File "corona-archiver.py", line 194, in _read_data_idx
    self._read_data_entry(offset, filename, True, True)
  File "corona-archiver.py", line 186, in _read_data_entry
    self._write_data_entry(content, offset if offset else self.stream.tell(), fi
lename)
  File "corona-archiver.py", line 211, in _write_data_entry
    new_filename = str(filename, 'utf-8')
TypeError: str() takes at most 1 argument (2 given)

**Comment by 0BuRner** [comment]
Hi, I made a fix 2 days ago to get compatibility with Python 3 but it seems I broke it with Python 2 x) Sorry...
I'm going to push the fix later today.

**Comment by bazickoff** [comment]
it's my fault :) it worked fine with python 3
 thank you for this amazing work
