### ISSUE TITLE
help with decompiling/decrypting

### ISSUE THREAD

**Issue by alidhkh** [0BuRner/corona-archiver#9]
Hi, thanks for this awesome tool.

After unpacking I got [these](https://github.com/alidhkh/lua) .lu files, but it seems that they are encrypted or compiled. 

I've tried a decompiler but it said invalid header, so I'm guessing they are encrypted.

Do you happen to have any information about it?

**Comment by 0BuRner** [comment]
Hi,
Check the following issue #3 I answer part of your question there. Your files are compiled. There are multiple Lua versions so maybe the decompiler you used doesn't work for the compiled file you have. Try another decompiler. I added some of them in the main page of this project (bottom of the page)
Hope it helps :)

**Comment by alidhkh** [comment]
You're awesome, unluac worked for me. I was trying other versions. It seems that in offset 1 of .lu files, Lua version is written. My files have luaQ, ASCII code of Q is: 51. So I had to use a 5.1 version. 
Thank you so much.
